# Katalog główny źródeł
TOPDIR=../..
# Katalog aplikacji
APPDIR=sbin
# Nazwa aplikacji
APPNAME=init
# Pliki źródłowe
SOURCES=init.c
# Biblioteki do zlinkowania
LDADD=
# Dodatkowe flagi kompilatora/linkera
LDFLAGS=
CFLAGS=

include $(TOPDIR)/scripts/application.mak
